### ISSUE TITLE
ERROR in NvD3Module is not an NgModule

### ISSUE THREAD

**Issue by rohamdi** [hendrathings/angular2-nvd3#1]
Hi,

with the lastest version of angular2 (and angular-cli), i am getting the error "ERROR in NvD3Module is not an NgModule" during compilation (dev serv, prod build and -aot compilation)

I don't know if the issue is angular2-nvd2's side or some other places, but i'am using other third-party modules and i only have this problem with yours so i thought that i would let you know.

for information :
$ ng -v
angular-cli: 1.0.0-beta.24
node: 6.9.2
os: win32 x64
@angular/common: 2.4.2
@angular/compiler: 2.4.2
@angular/core: 2.4.2
@angular/forms: 2.4.2
@angular/http: 2.4.2
@angular/platform-browser: 2.4.2
@angular/platform-browser-dynamic: 2.4.2
@angular/router: 3.4.2
@angular/compiler-cli: 2.4.2

and thanks for your hard work

**Comment by hendrathings** [comment]
Hi, it seem typescript version of angular-cli [issue ](https://github.com/angular/angular-cli/issues/3157).
Consider use [AngularClass/Starter](https://github.com/AngularClass/angular2-webpack-starter) at the moment. I will make support for angular-cli.

**Comment by rohamdi** [comment]
OKay, thanks, you can close the issue i guess.
I have another question, after i updated my data, how can i update the graph with your module? (it's not an issue but i can't manage to update it).

**Comment by hendrathings** [comment]
Here need to update::
```js
this.data = [
      {
        key: "Cumulative Return",
        values: [
          {
            "label" : "A" ,
            "value" : -29.765957771107
          } ,
          {
            "label" : "B" ,
            "value" : 0
          } ,
          {
            "label" : "C" ,
            "value" : 32.807804682612
          } ,
        ]
      }
    ];
```

**Comment by rohamdi** [comment]
my code was wrong, your module does the update automatically, my bad, and thanks for the answers.

**Comment by hendrathings** [comment]
This is issue come from [angular-cli with @angular/compiler-cli](https://github.com/angular/angular-cli/issues/3426#issuecomment-269669853).
