### ISSUE TITLE
Problem with @types/nvd3 package

### ISSUE THREAD

**Issue by Zefling** [hendrathings/angular2-nvd3#3]
Hi, 

Impossible to install the package, @types/nvd3 not found : 
```
npm ERR! 404 no such package available : @types/nvd3
npm ERR! 404 
npm ERR! 404  '@types/nvd3' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'angular2-nvd3'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url. 
```

**Comment by hendrathings** [comment]
Hi, [@types/nvd3](https://www.npmjs.com/package/@types/nvd3) already register. Please check here for any further: https://github.com/DefinitelyTyped/DefinitelyTyped.

Make sure your check by `npm search @types/nvd3` available or not.

**Comment by Zefling** [comment]
So sorry, it's a configuration problem of my sinopia: https://github.com/rlidwka/sinopia/issues/399#issuecomment-222623510
